export const EVENT_TYPES = {
  marriage: {
    name: 'Marriage',
    description: 'Elegant and formal catering for your wedding',
    image: '/elegant-wedding-catering-banquet-setup.jpg',
    bestCombinations: {
      lunch: ['biryani', 'paneer-tikka', 'naan', 'raita'],
      dinner: ['butter-chicken', 'dal-makhani', 'basmati-rice', 'gulab-jamun'],
    },
  },
  birthday: {
    name: 'Birthday Party',
    description: 'Fun and festive catering for celebrations',
    image: '/colorful-birthday-party-celebration-food-buffet.jpg',
    bestCombinations: {
      lunch: ['grilled-chicken', 'pasta', 'garlic-bread', 'salad'],
      dinner: ['tandoori-paneer', 'jeera-rice', 'naan', 'ice-cream'],
    },
  },
  corporate: {
    name: 'Corporate Event',
    description: 'Professional catering for business gatherings',
    image: '/professional-corporate-event-catering-business-mee.jpg',
    bestCombinations: {
      lunch: ['vegetable-pulao', 'tandoori-chicken', 'mixed-salad', 'dessert'],
      dinner: ['grilled-fish', 'saffron-rice', 'steamed-vegetables', 'cheesecake'],
    },
  },
};

export const DISHES = {
  'biryani': {
    id: 'biryani',
    name: 'Chicken Biryani',
    cost: 350,
    ingredients: ['Basmati Rice', 'Chicken', 'Saffron', 'Yogurt'],
    eventTypes: ['marriage', 'birthday'],
    image: '/chicken-biryani.png',
  },
  'paneer-tikka': {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    cost: 280,
    ingredients: ['Paneer', 'Yogurt', 'Spices', 'Bell Peppers'],
    eventTypes: ['marriage', 'birthday', 'corporate'],
    image: '/paneer-tikka-appetizer.png',
  },
  'naan': {
    id: 'naan',
    name: 'Butter Naan',
    cost: 80,
    ingredients: ['Flour', 'Butter', 'Yeast', 'Salt'],
    eventTypes: ['marriage', 'birthday', 'corporate'],
    image: '/butter-naan.png',
  },
  'raita': {
    id: 'raita',
    name: 'Cucumber Raita',
    cost: 60,
    ingredients: ['Yogurt', 'Cucumber', 'Cumin', 'Mint'],
    eventTypes: ['marriage', 'birthday'],
    image: '/cucumber-raita-yogurt-dip.jpg',
  },
  'butter-chicken': {
    id: 'butter-chicken',
    name: 'Butter Chicken',
    cost: 420,
    ingredients: ['Chicken', 'Cream', 'Tomato', 'Spices'],
    eventTypes: ['marriage', 'corporate'],
    image: '/butter-chicken-curry.png',
  },
  'dal-makhani': {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    cost: 200,
    ingredients: ['Lentils', 'Cream', 'Butter', 'Spices'],
    eventTypes: ['marriage', 'corporate'],
    image: '/dal-makhani-lentil-curry.jpg',
  },
  'basmati-rice': {
    id: 'basmati-rice',
    name: 'Basmati Rice',
    cost: 120,
    ingredients: ['Basmati Rice', 'Ghee', 'Spices'],
    eventTypes: ['marriage', 'corporate'],
    image: '/basmati-rice-white-rice.jpg',
  },
  'gulab-jamun': {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    cost: 150,
    ingredients: ['Milk Solids', 'Sugar', 'Rose Water', 'Cardamom'],
    eventTypes: ['marriage'],
    image: '/gulab-jamun-sweet-dessert.jpg',
  },
  'grilled-chicken': {
    id: 'grilled-chicken',
    name: 'Grilled Chicken',
    cost: 380,
    ingredients: ['Chicken', 'Herbs', 'Lemon', 'Garlic'],
    eventTypes: ['birthday', 'corporate'],
    image: '/grilled-chicken-steak.jpg',
  },
  'pasta': {
    id: 'pasta',
    name: 'Creamy Pasta',
    cost: 250,
    ingredients: ['Pasta', 'Cream', 'Garlic', 'Parmesan'],
    eventTypes: ['birthday'],
    image: '/creamy-pasta-alfredo.jpg',
  },
  'garlic-bread': {
    id: 'garlic-bread',
    name: 'Garlic Bread',
    cost: 100,
    ingredients: ['Bread', 'Garlic', 'Butter', 'Herbs'],
    eventTypes: ['birthday', 'corporate'],
    image: '/garlic-bread-toasted.jpg',
  },
  'salad': {
    id: 'salad',
    name: 'Mixed Salad',
    cost: 120,
    ingredients: ['Lettuce', 'Tomato', 'Cucumber', 'Dressing'],
    eventTypes: ['birthday', 'corporate'],
    image: '/mixed-salad-fresh-vegetables.jpg',
  },
  'tandoori-paneer': {
    id: 'tandoori-paneer',
    name: 'Tandoori Paneer',
    cost: 320,
    ingredients: ['Paneer', 'Yogurt', 'Spices', 'Lime'],
    eventTypes: ['birthday'],
    image: '/tandoori-paneer-grilled.jpg',
  },
  'jeera-rice': {
    id: 'jeera-rice',
    name: 'Jeera Rice',
    cost: 100,
    ingredients: ['Basmati Rice', 'Cumin', 'Ghee'],
    eventTypes: ['birthday'],
    image: '/jeera-rice-cumin-rice.jpg',
  },
  'ice-cream': {
    id: 'ice-cream',
    name: 'Premium Ice Cream',
    cost: 200,
    ingredients: ['Cream', 'Sugar', 'Milk', 'Flavoring'],
    eventTypes: ['birthday'],
    image: '/premium-ice-cream-dessert.jpg',
  },
  'vegetable-pulao': {
    id: 'vegetable-pulao',
    name: 'Vegetable Pulao',
    cost: 180,
    ingredients: ['Rice', 'Mixed Vegetables', 'Spices'],
    eventTypes: ['corporate'],
    image: '/placeholder.svg?height=150&width=150',
  },
  'tandoori-chicken': {
    id: 'tandoori-chicken',
    name: 'Tandoori Chicken',
    cost: 400,
    ingredients: ['Chicken', 'Yogurt', 'Spices', 'Charcoal'],
    eventTypes: ['corporate'],
    image: '/placeholder.svg?height=150&width=150',
  },
  'mixed-salad': {
    id: 'mixed-salad',
    name: 'Chef\'s Mixed Salad',
    cost: 140,
    ingredients: ['Greens', 'Vegetables', 'Dressing'],
    eventTypes: ['corporate'],
    image: '/placeholder.svg?height=150&width=150',
  },
  'dessert': {
    id: 'dessert',
    name: 'Assorted Desserts',
    cost: 250,
    ingredients: ['Various', 'Sugar', 'Flour'],
    eventTypes: ['corporate'],
    image: '/placeholder.svg?height=150&width=150',
  },
  'grilled-fish': {
    id: 'grilled-fish',
    name: 'Grilled Fish',
    cost: 500,
    ingredients: ['Fresh Fish', 'Herbs', 'Lemon', 'Olive Oil'],
    eventTypes: ['corporate'],
    image: '/placeholder.svg?height=150&width=150',
  },
  'saffron-rice': {
    id: 'saffron-rice',
    name: 'Saffron Rice',
    cost: 180,
    ingredients: ['Basmati Rice', 'Saffron', 'Ghee'],
    eventTypes: ['corporate'],
    image: '/placeholder.svg?height=150&width=150',
  },
  'steamed-vegetables': {
    id: 'steamed-vegetables',
    name: 'Steamed Vegetables',
    cost: 100,
    ingredients: ['Mixed Vegetables', 'Herbs', 'Spices'],
    eventTypes: ['corporate'],
    image: '/placeholder.svg?height=150&width=150',
  },
  'cheesecake': {
    id: 'cheesecake',
    name: 'Classic Cheesecake',
    cost: 300,
    ingredients: ['Cream Cheese', 'Graham Crackers', 'Sugar'],
    eventTypes: ['corporate'],
    image: '/placeholder.svg?height=150&width=150',
  },
};
